create table cats (id int4 generated by default as identity, date_of_birth timestamp, breed varchar(255), color varchar(255), name varchar(255), owner_id int4, primary key (id));
create table cats_friends (cat_id int4 not null, friend_id int4 not null);
create table owners (id int4 generated by default as identity, date_of_birth timestamp, name varchar(255), primary key (id));
alter table if exists cats add constraint FKc0phghv1jwbvelwan7pndwrei foreign key (owner_id) references owners;
alter table if exists cats_friends add constraint FK1wen44y0bpnqmdpmkwswsh6hu foreign key (friend_id) references cats;
alter table if exists cats_friends add constraint FKj7kirp45prm5e9is6srsd9j8k foreign key (cat_id) references cats;
